"""FastAPI entrypoint for the Vking v0.1 prototype web UI."""

from __future__ import annotations

import subprocess
import sys
import uuid
from pathlib import Path

from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse, HTMLResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field

from . import ai_generate, delta, doctor, ingest, runner, tbgen, waves
from .config import get_ai_config
from .ingest import parse_verilog_source
from .manifest import ArtifactPaths, GateResult, GateStatus, RunManifest
from .tbgen import TbGenConfig, generate_clk_rst_smoke

ROOT = Path(__file__).resolve().parent.parent
TEMPLATES = ROOT / "templates"
RUNS_DIR = ROOT / "runs"
DEMO_COUNTER = Path(__file__).resolve().parent / "demos" / "counter.v"

app = FastAPI(title="Vking Prototype", version="0.1.0")
RUNS_DIR.mkdir(parents=True, exist_ok=True)

if TEMPLATES.exists():
    app.mount("/static", StaticFiles(directory=str(TEMPLATES)), name="static")


class ParseRequest(BaseModel):
    source: str
    top_module: str | None = None


class RunRequest(BaseModel):
    source: str
    top_module: str | None = None
    tb_source: str | None = None


class SyncTbRequest(BaseModel):
    source: str


class AiGenerateRequest(BaseModel):
    source: str | None = None
    prompt: str | None = None
    mode: str = "generate"


class WavesRequest(BaseModel):
    run_id: str
    signals: list[str] | None = None


class DeltaRequest(BaseModel):
    run_id: str | None = None
    vcd_path: str | None = None
    time_ns: float = Field(default=100.0, ge=0)


class GtkwaveRequest(BaseModel):
    run_id: str | None = None
    wave_path: str | None = None


def _view_to_dict(view: ingest.ModuleView) -> dict:
    return {
        "module": view.name,
        "ports": [
            {
                "name": p.name,
                "direction": p.direction,
                "width": p.width_expr or "0",
            }
            for p in view.ports
        ],
        "parameters": view.parameters,
        "timescale": view.timescale,
        "errors": [],
    }


def _makefile_text(tb_top: str = "tb_top", wave: str = "waves.vcd") -> str:
    return f"""# Generated by Vking prototype
IVERILOG ?= iverilog
VVP ?= vvp
TOP ?= {tb_top}
WAVE ?= {wave}

all: sim

sim: run.vvp
\t$(VVP) -n -l run.log run.vvp

run.vvp: dut.v tb.v
\t$(IVERILOG) -g2012 -o $@ -s $(TOP) dut.v tb.v

waves:
\tgtkwave $(WAVE)

clean:
\trm -f run.vvp run.log $(WAVE)
"""


def _artifact_urls(manifest: RunManifest, run_dir: Path) -> dict[str, str]:
    rid = manifest.run_id
    base = f"/api/artifacts/{rid}"
    urls: dict[str, str] = {}
    paths = manifest.artifact_paths
    candidates = {
        "tb": paths.tb,
        "dut": paths.dut,
        "waves": paths.waves,
        "log": paths.sim_log or paths.log,
        "vvp": paths.vvp,
        "makefile": str(run_dir / "Makefile"),
        "filelist": str(run_dir / "filelist.f"),
    }
    for key, path in candidates.items():
        if path and Path(path).exists():
            urls[key] = f"{base}/{Path(path).name}"
    return urls


def _resolve_wave_path(run_id: str | None, wave_path: str | None) -> Path:
    if wave_path:
        p = Path(wave_path)
        if not p.is_absolute():
            p = RUNS_DIR / run_id / p.name if run_id else ROOT / p
        return p
    if not run_id:
        raise HTTPException(status_code=400, detail="run_id or wave_path required")
    run_dir = RUNS_DIR / run_id
    if not run_dir.exists():
        raise HTTPException(status_code=404, detail=f"run '{run_id}' not found")
    for name in ("waves.vcd", "waves.fst", "wave.vcd", "wave.fst"):
        candidate = run_dir / name
        if candidate.exists():
            return candidate
    raise HTTPException(status_code=404, detail="no waveform artifact for run")


@app.get("/", response_class=HTMLResponse)
def index() -> HTMLResponse:
    index_path = TEMPLATES / "index.html"
    if not index_path.exists():
        raise HTTPException(status_code=500, detail="templates/index.html missing")
    return HTMLResponse(index_path.read_text(encoding="utf-8"))


@app.get("/api/doctor")
def api_doctor() -> dict:
    return doctor.doctor_report()


@app.get("/api/demo/counter")
def api_demo_counter() -> dict:
    source = DEMO_COUNTER.read_text(encoding="utf-8") if DEMO_COUNTER.exists() else ""
    return {"source": source, "module": "counter"}


@app.post("/api/sync-tb")
def api_sync_tb(req: SyncTbRequest) -> dict:
    try:
        view = parse_verilog_source(req.source)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    cfg = TbGenConfig()
    try:
        tb_source = generate_clk_rst_smoke(view, cfg)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    return {
        "tb": tb_source,
        "module": view.name,
        "ports": _view_to_dict(view)["ports"],
    }


@app.post("/api/ai/generate")
def api_ai_generate(req: AiGenerateRequest) -> dict:
    if not get_ai_config():
        raise HTTPException(
            status_code=503,
            detail="no AI API key configured (set OPENROUTER_API_KEY or GROQ_API_KEY in .env)",
        )
    result = ai_generate.generate_verilog(
        source=req.source or "",
        prompt=req.prompt,
        mode=req.mode or "generate",
    )
    if not result.get("ok"):
        raise HTTPException(
            status_code=502,
            detail=result.get("error") or "AI generation failed",
        )
    return {
        "verilog": result["verilog"],
        "provider": result["provider"],
        "model": result["model"],
        "mode": result.get("mode", req.mode or "generate"),
    }


@app.post("/api/waves")
def api_waves(req: WavesRequest) -> dict:
    vcd = _resolve_wave_path(req.run_id, None)
    if vcd.suffix.lower() != ".vcd":
        raise HTTPException(
            status_code=400,
            detail="wave canvas requires VCD; this run has FST only",
        )
    return waves.build_wave_traces(vcd, signal_filter=req.signals)


@app.post("/api/parse")
def api_parse(req: ParseRequest) -> dict:
    try:
        view = parse_verilog_source(req.source)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    data = _view_to_dict(view)
    if req.top_module and view.name != req.top_module:
        data["errors"] = [f"top_module '{req.top_module}' does not match parsed '{view.name}'"]
    return data


@app.post("/api/run")
def api_run(req: RunRequest) -> dict:
    try:
        view = parse_verilog_source(req.source)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc

    cfg = TbGenConfig()
    if req.tb_source:
        tb_source = req.tb_source
    else:
        try:
            tb_source = generate_clk_rst_smoke(view, cfg)
        except ValueError as exc:
            raise HTTPException(status_code=400, detail=str(exc)) from exc
    health = doctor.doctor_report()

    if not health["sim_ready"]:
        rid = uuid.uuid4().hex[:12]
        run_dir = RUNS_DIR / rid
        run_dir.mkdir(parents=True, exist_ok=True)
        dut_path = run_dir / "dut.v"
        tb_path = run_dir / "tb.v"
        mk_path = run_dir / "Makefile"
        fl_path = run_dir / "filelist.f"
        dut_path.write_text(req.source, encoding="utf-8")
        tb_path.write_text(tb_source, encoding="utf-8")
        mk_path.write_text(_makefile_text(cfg.tb_top, cfg.wave_filename), encoding="utf-8")
        fl_path.write_text("dut.v\ntb.v\n", encoding="utf-8")

        manifest = RunManifest(
            run_id=rid,
            timestamp=runner._utc_now(),
            module=view.name,
            timescale=view.timescale or cfg.timescale,
            backend_version=None,
            artifact_paths=ArtifactPaths(
                dut=str(dut_path),
                tb=str(tb_path),
                waves=str(run_dir / cfg.wave_filename),
                sim_log=str(run_dir / "run.log"),
            ),
        )
        for gate, msg in (
            ("G0", "verilator not on PATH"),
            ("G1", "iverilog/vvp not on PATH"),
            ("G1.5", "compile skipped"),
            ("G2", "sim skipped"),
        ):
            manifest.gate_results[gate] = GateResult(
                gate=gate,
                status=GateStatus.SKIP,
                message=msg,
                backend="iverilog" if gate != "G0" else "verilator",
            )
        manifest.write_json(run_dir / "manifest.json")
        manifest_dict = manifest.model_dump(mode="json")
        return {
            "manifest": manifest_dict,
            "log": health.get("install_hint") or "Toolchain missing — artifacts generated, sim skipped.",
            "artifact_paths": manifest.artifact_paths.model_dump(),
            "artifact_urls": _artifact_urls(manifest, run_dir),
            "ports": _view_to_dict(view)["ports"],
        }

    rid = uuid.uuid4().hex[:12]
    run_dir = RUNS_DIR / rid
    run_dir.mkdir(parents=True, exist_ok=True)
    dut_path = run_dir / "dut.v"
    dut_path.write_text(req.source, encoding="utf-8")

    try:
        manifest, run_dir = runner.run_simulation(
            dut_path,
            tb_source=tb_source,
            view=view,
            tb_config=cfg,
            runs_root=RUNS_DIR,
            run_id=rid,
        )
    except RuntimeError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc

    mk_path = run_dir / "Makefile"
    fl_path = run_dir / "filelist.f"
    mk_path.write_text(_makefile_text(cfg.tb_top, cfg.wave_filename), encoding="utf-8")
    fl_path.write_text("dut.v\ntb.v\n", encoding="utf-8")

    log_path = manifest.artifact_paths.sim_log
    log_text = Path(log_path).read_text(encoding="utf-8") if log_path and Path(log_path).exists() else ""

    manifest_dict = manifest.model_dump(mode="json")
    return {
        "manifest": manifest_dict,
        "log": log_text,
        "artifact_paths": manifest.artifact_paths.model_dump(),
        "artifact_urls": _artifact_urls(manifest, run_dir),
        "ports": _view_to_dict(view)["ports"],
    }


@app.get("/api/artifacts/{run_id}/{filename}")
def api_artifacts(run_id: str, filename: str) -> FileResponse:
    path = RUNS_DIR / run_id / filename
    if not path.exists() or not path.is_file():
        raise HTTPException(status_code=404, detail="artifact not found")
    return FileResponse(path, filename=filename)


@app.post("/api/delta")
def api_delta(req: DeltaRequest) -> dict:
    vcd: Path | None = None
    if req.vcd_path:
        vcd = Path(req.vcd_path)
        if not vcd.is_absolute() and req.run_id:
            vcd = RUNS_DIR / req.run_id / vcd.name
    elif req.run_id:
        run_dir = RUNS_DIR / req.run_id
        for name in ("waves.vcd", "wave.vcd", "dump.vcd"):
            candidate = run_dir / name
            if candidate.exists():
                vcd = candidate
                break
        if vcd is None:
            fst = run_dir / "waves.fst"
            if fst.exists():
                return delta.reconstruct(fst, req.time_ns)
            return {
                "available": False,
                "message": "no VCD for this run — delta panel needs VCD (prototype uses VCD, not FST)",
                "time_ns": req.time_ns,
                "rows": [],
            }
    else:
        raise HTTPException(status_code=400, detail="run_id or vcd_path required")

    return delta.reconstruct(vcd, req.time_ns)


@app.post("/api/gtkwave")
def api_gtkwave(req: GtkwaveRequest) -> dict:
    health = doctor.doctor_report()
    if not health["tools"]["gtkwave"]["available"]:
        raise HTTPException(
            status_code=503,
            detail="gtkwave not on PATH — install oss-cad-suite",
        )

    wave = _resolve_wave_path(req.run_id, req.wave_path)
    if not wave.exists():
        raise HTTPException(status_code=404, detail=f"wave file not found: {wave}")

    gtkwave = health["tools"]["gtkwave"]["path"] or "gtkwave"
    cmd = [gtkwave, str(wave.resolve())]

    try:
        if sys.platform == "win32":
            subprocess.Popen(
                cmd,
                creationflags=subprocess.DETACHED_PROCESS
                | subprocess.CREATE_NEW_PROCESS_GROUP,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                close_fds=True,
            )
        else:
            subprocess.Popen(
                cmd,
                start_new_session=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
    except OSError as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc

    return {"launched": True, "wave_path": str(wave), "command": cmd}


def main() -> None:
    import uvicorn

    uvicorn.run("vking_proto.app:app", host="127.0.0.1", port=8765, reload=False)


if __name__ == "__main__":
    main()
